// <auto-generated />
using System;
using FleetManager.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FleetManager.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251118160530_ParcheggioInitial")]
    partial class ParcheggioInitial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FleetManager.Models.Manutenzione", b =>
                {
                    b.Property<int>("ManutenzioneID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ManutenzioneID"));

                    b.Property<decimal>("Costo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descrizione")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Stato")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VeicoloID")
                        .HasColumnType("int");

                    b.HasKey("ManutenzioneID");

                    b.HasIndex("VeicoloID");

                    b.ToTable("Manutenzioni");
                });

            modelBuilder.Entity("FleetManager.Models.PostoAuto", b =>
                {
                    b.Property<int>("PostoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PostoID"));

                    b.Property<string>("CodicePosto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Stato")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PostoID");

                    b.ToTable("PostiAuto");
                });

            modelBuilder.Entity("FleetManager.Models.Prenotazione", b =>
                {
                    b.Property<int>("PrenotazioneID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PrenotazioneID"));

                    b.Property<DateTime>("DataFinePrevista")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataInizioRichiesta")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Scopo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Stato")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UtenteID")
                        .HasColumnType("int");

                    b.Property<int>("VeicoloID")
                        .HasColumnType("int");

                    b.HasKey("PrenotazioneID");

                    b.HasIndex("UtenteID");

                    b.HasIndex("VeicoloID");

                    b.ToTable("Prenotazioni");
                });

            modelBuilder.Entity("FleetManager.Models.Segnalazione", b =>
                {
                    b.Property<int>("SegnalazioneID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SegnalazioneID"));

                    b.Property<DateTime>("DataSegnalazione")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descrizione")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PostoID")
                        .HasColumnType("int");

                    b.Property<string>("RispostaAdmin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Stato")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UtenteID")
                        .HasColumnType("int");

                    b.Property<int?>("VeicoloID")
                        .HasColumnType("int");

                    b.HasKey("SegnalazioneID");

                    b.HasIndex("PostoID");

                    b.HasIndex("UtenteID");

                    b.HasIndex("VeicoloID");

                    b.ToTable("Segnalazioni");
                });

            modelBuilder.Entity("FleetManager.Models.Utente", b =>
                {
                    b.Property<int>("UtenteID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UtenteID"));

                    b.Property<string>("Cognome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataNascita")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataRegistrazione")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ruolo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UtenteID");

                    b.ToTable("Utenti");
                });

            modelBuilder.Entity("FleetManager.Models.Veicolo", b =>
                {
                    b.Property<int>("VeicoloId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VeicoloId"));

                    b.Property<DateTime>("DataRegistrazione")
                        .HasColumnType("datetime2");

                    b.Property<int>("LivelloCarburante")
                        .HasColumnType("int");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Modello")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PostoID")
                        .HasColumnType("int");

                    b.Property<string>("Stato")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Targa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VeicoloId");

                    b.HasIndex("PostoID");

                    b.ToTable("Veicoli");
                });

            modelBuilder.Entity("FleetManager.Models.Manutenzione", b =>
                {
                    b.HasOne("FleetManager.Models.Veicolo", "Veicolo")
                        .WithMany()
                        .HasForeignKey("VeicoloID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Veicolo");
                });

            modelBuilder.Entity("FleetManager.Models.Prenotazione", b =>
                {
                    b.HasOne("FleetManager.Models.Utente", "Utente")
                        .WithMany()
                        .HasForeignKey("UtenteID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FleetManager.Models.Veicolo", "Veicolo")
                        .WithMany()
                        .HasForeignKey("VeicoloID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utente");

                    b.Navigation("Veicolo");
                });

            modelBuilder.Entity("FleetManager.Models.Segnalazione", b =>
                {
                    b.HasOne("FleetManager.Models.PostoAuto", "PostoAuto")
                        .WithMany()
                        .HasForeignKey("PostoID");

                    b.HasOne("FleetManager.Models.Utente", "Utente")
                        .WithMany()
                        .HasForeignKey("UtenteID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FleetManager.Models.Veicolo", "Veicolo")
                        .WithMany()
                        .HasForeignKey("VeicoloID");

                    b.Navigation("PostoAuto");

                    b.Navigation("Utente");

                    b.Navigation("Veicolo");
                });

            modelBuilder.Entity("FleetManager.Models.Veicolo", b =>
                {
                    b.HasOne("FleetManager.Models.PostoAuto", "PostoAuto")
                        .WithMany()
                        .HasForeignKey("PostoID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("PostoAuto");
                });
#pragma warning restore 612, 618
        }
    }
}
