// <auto-generated />
using System;
using FleetManager.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FleetManager.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251120235105_RendereOraRilascioNullable")]
    partial class RendereOraRilascioNullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FleetManager.Models.DashboardSnapshot", b =>
                {
                    b.Property<int>("DashboardSnapshotID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DashboardSnapshotID"));

                    b.Property<DateTime>("Giorno")
                        .HasColumnType("datetime2");

                    b.Property<int>("ManutenzioniAperte")
                        .HasColumnType("int");

                    b.Property<int>("PrenotazioniAttive")
                        .HasColumnType("int");

                    b.Property<int>("SegnalazioniAperte")
                        .HasColumnType("int");

                    b.Property<int>("VeicoliDisponibili")
                        .HasColumnType("int");

                    b.Property<int>("VeicoliInManutenzione")
                        .HasColumnType("int");

                    b.Property<int>("VeicoliInUso")
                        .HasColumnType("int");

                    b.Property<int>("VeicoliTotali")
                        .HasColumnType("int");

                    b.HasKey("DashboardSnapshotID");

                    b.ToTable("DashboardSnapshots");
                });

            modelBuilder.Entity("FleetManager.Models.Segnalazione", b =>
                {
                    b.Property<int>("SegnalazioneID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SegnalazioneID"));

                    b.Property<DateTime>("DataCreazione")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descrizione")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PostoID")
                        .HasColumnType("int");

                    b.Property<string>("Stato")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UtenteID")
                        .HasColumnType("int");

                    b.Property<int?>("VeicoloID")
                        .HasColumnType("int");

                    b.HasKey("SegnalazioneID");

                    b.HasIndex("UtenteID");

                    b.HasIndex("VeicoloID");

                    b.ToTable("Segnalazioni");
                });

            modelBuilder.Entity("FleetManager.Models.Utente", b =>
                {
                    b.Property<int>("UtenteID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UtenteID"));

                    b.Property<string>("Cognome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataNascita")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataRegistrazione")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ruolo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UtenteID");

                    b.ToTable("Utenti");
                });

            modelBuilder.Entity("FleetManager.Models.Veicolo", b =>
                {
                    b.Property<int>("VeicoloId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VeicoloId"));

                    b.Property<string>("Carburante")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Cilindrata")
                        .HasColumnType("int");

                    b.Property<string>("Colore")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DataAggiornamento")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCreazione")
                        .HasColumnType("datetime2");

                    b.Property<int>("LivelloCarburante")
                        .HasColumnType("int");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Modello")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("PostoAuto")
                        .HasColumnType("int");

                    b.Property<string>("Stato")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Targa")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("UtenteManutentoreID")
                        .HasColumnType("int");

                    b.Property<int?>("UtentePrenotatoID")
                        .HasColumnType("int");

                    b.HasKey("VeicoloId");

                    b.HasIndex("UtenteManutentoreID");

                    b.HasIndex("UtentePrenotatoID");

                    b.ToTable("Veicoli");
                });

            modelBuilder.Entity("Manutenzione", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DataFine")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataInizio")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descrizione")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UtenteId")
                        .HasColumnType("int");

                    b.Property<int>("VeicoloId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UtenteId");

                    b.HasIndex("VeicoloId");

                    b.ToTable("Manutenzioni");
                });

            modelBuilder.Entity("Prenotazione", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("OraPrenotazione")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("OraRilascio")
                        .HasColumnType("datetime2");

                    b.Property<int>("UtenteId")
                        .HasColumnType("int");

                    b.Property<int>("VeicoloId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UtenteId");

                    b.HasIndex("VeicoloId");

                    b.ToTable("Prenotazioni");
                });

            modelBuilder.Entity("FleetManager.Models.Segnalazione", b =>
                {
                    b.HasOne("FleetManager.Models.Utente", "Utente")
                        .WithMany("Segnalazioni")
                        .HasForeignKey("UtenteID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FleetManager.Models.Veicolo", "Veicolo")
                        .WithMany("Segnalazioni")
                        .HasForeignKey("VeicoloID");

                    b.Navigation("Utente");

                    b.Navigation("Veicolo");
                });

            modelBuilder.Entity("FleetManager.Models.Veicolo", b =>
                {
                    b.HasOne("FleetManager.Models.Utente", "UtenteManutentore")
                        .WithMany()
                        .HasForeignKey("UtenteManutentoreID");

                    b.HasOne("FleetManager.Models.Utente", "UtentePrenotato")
                        .WithMany()
                        .HasForeignKey("UtentePrenotatoID");

                    b.Navigation("UtenteManutentore");

                    b.Navigation("UtentePrenotato");
                });

            modelBuilder.Entity("Manutenzione", b =>
                {
                    b.HasOne("FleetManager.Models.Utente", "Utente")
                        .WithMany("Manutenzioni")
                        .HasForeignKey("UtenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FleetManager.Models.Veicolo", "Veicolo")
                        .WithMany("Manutenzioni")
                        .HasForeignKey("VeicoloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utente");

                    b.Navigation("Veicolo");
                });

            modelBuilder.Entity("Prenotazione", b =>
                {
                    b.HasOne("FleetManager.Models.Utente", "Utente")
                        .WithMany("Prenotazioni")
                        .HasForeignKey("UtenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FleetManager.Models.Veicolo", "Veicolo")
                        .WithMany("Prenotazioni")
                        .HasForeignKey("VeicoloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utente");

                    b.Navigation("Veicolo");
                });

            modelBuilder.Entity("FleetManager.Models.Utente", b =>
                {
                    b.Navigation("Manutenzioni");

                    b.Navigation("Prenotazioni");

                    b.Navigation("Segnalazioni");
                });

            modelBuilder.Entity("FleetManager.Models.Veicolo", b =>
                {
                    b.Navigation("Manutenzioni");

                    b.Navigation("Prenotazioni");

                    b.Navigation("Segnalazioni");
                });
#pragma warning restore 612, 618
        }
    }
}
